name: CI

on:
  push:
  pull_request:
  repository_dispatch:
    types: [trigger-workflow]
  schedule:
    - cron: '0 0 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  ci:
    name: Building ${{ matrix.file }} / ${{ matrix.esphome-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        #### Modify below here to match your project ####
        include:
          - file: projects/xiao_2_channel_wifi_ac_energy_meter/xiao_2_channel_wifi_ac_energy_meter
            esphome-version: stable
          - file: projects/seeedstudio-iot-button/seeedstudio-iot-button
            esphome-version: stable
          - file: projects/xiao-soil-moisture-monitor/xiao-soil-moisture-monitor
            esphome-version: stable
          - file: projects/xiao_smart_ir_mate/xiao_smart_ir_mate
            esphome-version: dev
          #- projects/xiao_24ghz_mmwave/xiao_24ghz_mmwave
        #### Modify above here to match your project ####

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4.2.2
      - name: ESPHome ${{ matrix.esphome-version }}
        uses: esphome/build-action@v7.0.0
        with:
          yaml-file: ${{ matrix.file }}.yaml
          version: ${{ matrix.esphome-version }}